version: '3.4'

services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    # volumes:
    #   - /tmp/redis:/data

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    command: npm run dev
    volumes:
      - ./src:/app/src
    env_file: ./.docker.env
